[package]
name = "parity-db"
version = "0.2.3"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/parity-db/"
description = "Key-value database for the blockchain"

[dependencies]
log = "0.4.8"
parking_lot = "0.11	"
memmap2 = "0.2"
blake2-rfc = "0.2.18"
libc = "0.2"
crc32fast = "1.2.0"
rand = "0.8.2"
hex = "0.4.2"
fs2 = "0.4.3"
lz4 = "1.23.2"
zstd = "0.7.0"
snap = "1.0.4"
snappy = "0.4.0"
structopt = { version = "0.3.8", optional = true }
env_logger = { version = "0.8.3", optional = true }
# TODO remove this dependency (move code to admin
# or admin command ot bench/bin).
db-bench = { path = "bench/core", optional = true }

# TODO could also gat behind admin feature.
[target.'cfg(all(not(windows), not(target_env = "musl")))'.dependencies]
jemallocator = "0.3.0"

[dev-dependencies]
env_logger = "0.8.2"

[profile.release]
panic = "abort"
codegen-units = 1
lto = "fat"
debug = true

[workspace]
members = [
	".",
	"bench/core",
	"bench/bin",
]

[features]
default = [
# TODO remove this from default
  "admin",
]
admin = [
	"structopt",
	"env_logger",
	"db-bench",
]
